export const CONTACT_LIST_REQUEST = 'CONTACT_LIST_REQUEST';
export const CONTACT_LIST_SUCCESS = 'CONTACT_LIST_SUCCESS';
export const CONTACT_LIST_FAIL = 'CONTACT_LIST_FAIL';
export const CONTACT_LIST_RESET = 'CONTACT_LIST_RESET';


export const CHAT_TABLE_REQUEST = 'CHAT_TABLE_REQUEST';
export const CHAT_TABLE_SUCCESS = 'CHAT_TABLE_SUCCESS';
export const CHAT_TABLE_FAIL = 'CHAT_TABLE_FAIL';
export const CHAT_TABLE_RESET = 'CHAT_TABLE_RESET';


export const CHAT_CREATE_REQUEST = 'CHAT_CREATE_REQUEST';
export const CHAT_CREATE_SUCCESS = 'CHAT_CREATE_SUCCESS';
export const CHAT_CREATE_FAIL = 'CHAT_CREATE_FAIL';
export const CHAT_CREATE_RESET = 'CHAT_CREATE_RESET';


export const CHAT_FEATCH_REQUEST = 'CHAT_FEATCH_REQUEST';
export const CHAT_FEATCH_SUCCESS = 'CHAT_FEATCH_SUCCESS';
export const CHAT_FEATCH_FAIL = 'CHAT_FEATCH_FAIL';
export const CHAT_FEATCH_RESET = 'CHAT_FEATCH_RESET';


export const CHAT_LIST_REQUEST = 'CHAT_LIST_REQUEST';
export const CHAT_LIST_SUCCESS = 'CHAT_LIST_SUCCESS';
export const CHAT_LIST_FAIL = 'CHAT_LIST_FAIL';
export const CHAT_LIST_RESET = 'CHAT_LIST_RESET';