export const CONTACT_LIST_REQUEST = 'CONTACT_LIST_REQUEST';
export const CONTACT_LIST_SUCCESS = 'CONTACT_LIST_SUCCESS';
export const CONTACT_LIST_FAIL = 'CONTACT_LIST_FAIL';
export const CONTACT_LIST_RESET = 'CONTACT_LIST_RESET';


export const CHAT_TABLE_REQUEST = 'CHAT_TABLE_REQUEST';
export const CHAT_TABLE_SUCCESS = 'CHAT_TABLE_SUCCESS';
export const CHAT_TABLE_FAIL = 'CHAT_TABLE_FAIL';
export const CHAT_TABLE_RESET = 'CHAT_TABLE_RESET';


export const CHAT_CREATE_REQUEST = 'CHAT_CREATE_REQUEST';
export const CHAT_CREATE_SUCCESS = 'CHAT_CREATE_SUCCESS';
export const CHAT_CREATE_FAIL = 'CHAT_CREATE_FAIL';
export const CHAT_CREATE_RESET = 'CHAT_CREATE_RESET';

export const CHAT_UPLOADIMG_REQUEST = 'CHAT_UPLOADIMG_REQUEST';
export const CHAT_UPLOADIMG_SUCCESS = 'CHAT_UPLOADIMG_SUCCESS';
export const CHAT_UPLOADIMG_FAIL = 'CHAT_UPLOADIMG_FAIL';
export const CHAT_UPLOADIMG_RESET = 'CHAT_UPLOADIMG_RESET';


export const CHAT_FETCH_REQUEST = 'CHAT_FETCH_REQUEST';
export const CHAT_FETCH_SUCCESS = 'CHAT_FETCH_SUCCESS';
export const CHAT_FETCH_FAIL = 'CHAT_FETCH_FAIL';
export const CHAT_FETCH_RESET = 'CHAT_FETCH_RESET';


export const CHAT_LIST_REQUEST = 'CHAT_LIST_REQUEST';
export const CHAT_LIST_SUCCESS = 'CHAT_LIST_SUCCESS';
export const CHAT_LIST_FAIL = 'CHAT_LIST_FAIL';
export const CHAT_LIST_RESET = 'CHAT_LIST_RESET';

export const UPDATE_OPPONENT_DATA = 'UPDATE_OPPONENT_DATA';